### PR TITLE
feat(server): Add Redis docker image

### PR DESCRIPTION
**Pull request by vhf**
I wasn't sure about which commit prefix to use here. Please tell me what you'd have chosen.

### CODE REVIEW

**Comment by marcbachmann** [comment]
Most likely `feat` or `feat` and `BREAKING CHANGE` because people won't be able to work with the server unless they update their docker compose files.

**Comment by masone** [comment]
I would probably have used `feat`, but that's not a biggie
Once merged, this will push a new `@livingdocs/docker` package to npm, which you then can install in the server. A `li-docker install` will install the new docker files. Downstream will have to run that command too

**Comment by masone** [comment]
The `BREAKING CHANGE` should be issued in the server repository, not here. For this project, it's not a breaking change. Nothing here relies on redis

**Comment by marcbachmann** [comment]
It's a bigger change to add a whole new database, which might also be a security leak if their firewall isn't set up properly, so I'd use it to make people aware of that.

**Comment by vhf** [comment]
Here goes: feat + breaking.

New round of review please.

**Pull request merged**
